---
# tasks file for prometheus-blackbox-exporter
- name: Assert that blackbox_machine_arch is set
  ansible.builtin.assert:
    that:
      - blackbox_machine_arch is defined
      - blackbox_machine_arch | trim | length > 0
    fail_msg: >
      Error: blackbox_machine_arch is empty. 
      This could be because the target system is neither amd64 nor arm64"

- debug:
    msg: "{{ ansible_os_family }}"

- name: Debian/RedHat - Deploy Prometheus Blackbox Exporter
  ansible.builtin.include_tasks: common/main.yml
  when:
    - ansible_os_family in ['Debian', 'RedHat']
    - 'action == "install"'
