- name: Stop Blackbox exporter service
  ansible.builtin.service:
    name: prometheus-blackbox-exporter
    state: stopped

- name: Remove Blackbox exporter files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/usr/bin/prometheus-blackbox-exporter"
    - "/etc/default/prometheus-blackbox-exporter"
    - "{{ blackbox_configuration_path }}/blackbox.yml"
    - "{{ blackbox_remote_package_path }}/blackbox_exporter-{{ blackbox_exporter_version }}.linux-{{ blackbox_machine_arch }}/"

- name: Check if blackbox configuration director is empty
  ansible.builtin.find:
    paths: "{{ blackbox_configuration_path }}/"
    patterns: "*"
    recurse: true
  register: blackbox_config_dir_files

- name: Remove blackbox configuration directory if empty
  ansible.builtin.file:
    path: "{{ blackbox_configuration_path }}/"
    state: absent
  when: blackbox_config_dir_files.files | length == 0

- name: Remove the blackbox service file
  ansible.builtin.file:
    path: /lib/systemd/system/prometheus-blackbox-exporter.service
    state: absent